default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  user: usr
  password: 123456

development:
  <<: *default
  database: qa_development

test:
  <<: *default
  database: qa_test

production:
  <<: *default
  database: qa_production
#  username: qna
#  password: <%= ENV['QNA_DATABASE_PASSWORD'] %>
